### ISSUE TITLE
86Box process isn't detected when starting VM

### ISSUE THREAD

**Issue by ts-korhonen** [laciba96/WinBox-Reloaded#1]
Starting a VM launches 86Box correctly, but Winbox doesn't update from "Starting..." and goes to "Stopped" if update list is pressed. Same thing happens with all VM's I've created.

I'm using Windows 10 Pro ver. 2004 (English language, Finnish regional settings)

Winbox installed itself in:
`C:\Users\Teemu\AppData\Roaming\Laci bá'\WinBox`

VM's are in:
`F:\My Documents\WinBox virtual machines`

It launches 86Box with command line:
`"C:\Users\Teemu\AppData\Roaming\Laci bá'\WinBox\86Box\86Box.exe" --vmpath "F:\My Documents\WinBox virtual machines\{BC562109-F8C4-4392-B4B6-FB41CB1180C1}"`

Screenshot after launcing VM (and 86Box is running normally):
![image](https://user-images.githubusercontent.com/80648513/118482960-1db16900-b71e-11eb-9e1e-6c3cbeb08f02.png)

Profile settings:
![image](https://user-images.githubusercontent.com/80648513/118482786-e478f900-b71d-11eb-96e4-ee6a9c814505.png)

**Comment by laciba96** [comment]
I created a new release which hopefully fixes your problem.

To determine what could be the problem in the code, I recreated the same environment what you wrote, and I also noticed this bug. For me the new release solved it in this environment, but please confirm it, that it's also works for you too.

**Comment by ts-korhonen** [comment]
Didn't fix it for me, still the same behavior with the new release.

**Comment by ts-korhonen** [comment]
I tried with my laptop too, exactly the same result. It has Windows 10 Home v.2004.

Something different did happen when creating VM, this error popped up while it still went through with it:
![image](https://user-images.githubusercontent.com/80648513/118693252-92b29a80-b813-11eb-83fd-1fb30c4407dc.png)

**Comment by laciba96** [comment]
> 
> 
> Didn't fix it for me, still the same behavior with the new release.

It's sad to hear this but I added some debug features to the program for this case. If you have some free time, you may try this because it gives me very useful informations, and I may solve the problem.

To do this, you have to attach a debugger to the program of your choice, and catch it's debugger messages. This also adds a new menu which contains logging features. I tested with Delphi, and Nir Sofer's SimpleProgramDebugger + SysInternal DbgView and both worked, but I guess any other kind of debugger does the work, which can get debug output from a program.

![kép](https://user-images.githubusercontent.com/84271678/118700891-6a2aa080-b813-11eb-91ba-56b79e7d8a66.png)

If I check all the options on my PC, I got a such log from DbgView.

[LACIBA-PC.LOG](https://github.com/laciba96/WinBox-Reloaded/files/6503331/LACIBA-PC.LOG)

If you send me a log like this I can guess where my program fails, and which part of the code can cause the bug for you .

Also if you have started the 86Box, and it runs properly, you can get a full list of the processes that WinBox can discover, and you can signal me back, that is your 86Box instance on the list at all.

I know that is a lot of stuff, but if you can give me these information I could continue finding the cause of the error. Today I watched the whole process monitoring line-by-line, and I fixed many little bugs, but to be honest - right now I'm out of ideas, and these logs can give advice, where is the bug that makes the program unusable for you.

**Comment by ts-korhonen** [comment]
Here is the log. I used gdb.
[winbox-gdb-output.txt](https://github.com/laciba96/WinBox-Reloaded/files/6503672/winbox-gdb-output.txt)

If dumping the process list there are no 86Box processes in it even if there are some running. I tried also starting 86Box from it's normal manager and those didn't show up either.

**Comment by laciba96** [comment]
> 
> 
> Ok, I looked at the process list, it was long. Closed a bunch of processes (chrome had alot), and now it's working. So maybe the process list get truncated when there's enough stuff running.
> 
> edit: and now after starting Chrome to write this, it stopped working.
> 
> edit2: seems Winbox only sees the first ~101 processes in starting order and if 86Box.exe is past that, it won't work.

It seems to me that this ~101 list limit shows the spot for the real problem. The log file shows me the same you described, it acts like if the 86Box is missing from the running processes list.

In the ProcessMon.pas I used a fixed size buffer which can store 1024 Process IDs, but I looked this code part closer from now, and I've found that I wrongly passed the array length in the cb parameter to the [EnumProcesses](https://docs.microsoft.com/en-us/windows/win32/api/psapi/nf-psapi-enumprocesses) function, while it wants the array size, and not the length. 

I increased to buffer length so it can contain 2048 PIDs from now, and corrected the cb parameter to 2048 * sizeof(dword). I commited the change, and I tested it with 136 processes, and it listed properly all of them now. After I found a solution to #3 I make another release, so you can check that this fix means a solution to your problem, or it will persists.

**Comment by laciba96** [comment]
I uploaded a new release which theoretically fixes both #3 and #1. Could you indicate back if this is indeed solves the problems?

**Comment by laciba96** [comment]
I uploaded to VirusTotal and it said 4/67, but yes will I recompile it, and also add fix #5.

**Comment by ts-korhonen** [comment]
It works now in the -fix3.1 release even with approximately the same amount of processes running.
