### ISSUE TITLE
Imported VM is deleted from source path

### ISSUE THREAD

**Issue by tomrune** [laciba96/WinBox-Reloaded#12]
I imported an 86Box VM into WinBox and it deleted the old VM files. As the imported VM could not be configured, I deleted the VM in Winbox, and thus I lost the VM. 

I had a backup of it, so I was able to recover, but I would like if the user was prompted or there was a setting not to delete imported VMs.

**Comment by laciba96** [comment]
Yes, that's the behaviour right now, because if the imported VMs act as VMs created in WinBox.

> I would like if the user was prompted or there was a setting not to delete imported VMs.

It's a good idea, since when I imported my VMs I clicked Yes on the deletion confirmation, I also almostly deleted them - but since the program only moves the files to Recycle Bin, on my PC there was no data loss. 

In a future update (hopefully the next update) I want to distinguish the imported VMs and the created VMs - and an option for disabling the removal of files for imported VMs sounds me a good idea.

Since it not a bug, just a strangely realized UI till this next update arrives, you can avoid this behavior by clicking the No button at the delete confirmation dialog, and next time it will keeps the files, and only removes the entry from the list.
