### ISSUE TITLE
Uploading 86box VMs through the internet?

### ISSUE THREAD

**Issue by JustinJ553** [laciba96/WinBox-Reloaded#14]
Now this could be the craziest idea i've ever seen in my mind.

I was thinking if we can upload our virtual machines including the configs & virtual hard drives to the server (we need one server/site for that)? As i said "craziest idea", this could be useful if we can share our setups.

There will be a menu after you right click the VM from Winbox's right tab. Inside the menu you can customize the vm icon, its name, the creator/author of machine setup. And finally, locate your hard disk on "Other Disk Images" or elsewhere.

After uploading, your 86box vm will be uploaded on the server and placed in "Download VMs" menu on the Winbox upper tab. ~~There will be a list there depending what setup is using the machine templates.~~

**Comment by laciba96** [comment]
The idea is good, but I don't know what is possible in these scenarios, and what not. As for the grand rework I can add an author field to the VMs, it don't cost me so much effort.

The first thing this suggestion needs is a proper backup and restore system, which currently WinBox lacks of. It could be more complicated than it sounds first, even if someone uses differential VHDs, to track down all the parent disks, keep the relative paths, etc.

If the backup and restore features will be created in the far future, you can exchange or create preinstalled VMs with your friends on the internet. Since I can't check that everyone who wants to download it has original keys, install media, and etc., I would like to avoid integrating such a Download VM feature.

The thing I would offer after the grand rework is a proper documentation, and support of custom templates. There are some code snippets right now for supporting it. If someone has an unchanged old machine, and can configure 86Box by itself, the documentation will shows the steps, how it can be converted to a template file.

Also I want to achieve that if someone want to share his/her properly working custom templates, make some opportunity to send pull requests, and WinBox will download the added templates from the GitHub page with the next auto-update. This is my plan for the near future, and I want to introduce it with the grand update.
