### ISSUE TITLE
WICBitmapInterpolationModeHighQualityCubic

### ISSUE THREAD

**Issue by limelect** [laciba96/WinBox-Reloaded#4]
D10.2.3
WICBitmapInterpolationModeHighQualityCubic   missing

**Comment by laciba96** [comment]
I use Delphi 10.3 (v26.0) to build the project, and the Winapi.Wincodec.pas contains this constant for me.
You may try adding these lines to uCommUtil.pas, but you can run to other problems caused by the different IDE and library versions.

```
const
  WICBitmapInterpolationModeHighQualityCubic = 4;
  {$EXTERNALSYM WICBitmapInterpolationModeHighQualityCubic}
```
With the same exact Delphi version, if you installed the package in SajatU and added the paths to library it should compile without problems.
