### ISSUE TITLE
Share the same 86box general settings

### ISSUE THREAD

**Issue by JustinJ553** [laciba96/WinBox-Reloaded#9]
When you created your second or more virtual machines, it will use/keep the same general configs (like HiDpi or Overscan) from first created machine.

**Comment by laciba96** [comment]
Yes it's true because the program automatically writes these settings to the new VMs.

[General]
video_fullscreen_first=0
video_fullscreen_scale=1
dpi_scale=0
vid_resize=2
window_fixed_res=960x720 or from the setting from Template (like Toshiba PC-s)

The reason I write this settings to 86box.cfg in every creation, because in my opinion these settings provides the best appearance on VMs, and I set these settings up every time on a new 86Box VM.

Since these settings are VM specific, you can change it in the emulator if you don't like it, and it saves and keep your settings.

Is this behaviour you mentioned? Should I change it in future releases?

**Comment by JustinJ553** [comment]
Ye.

Sometimes people kinda need to keep their preferences. You probably have that as an option if they wanted to, during creating your new virtual machine before finishing your steps.

**Comment by laciba96** [comment]
The solution I can offer, that I can add a new tab to the Program Settings dialog, where:
  a, This feature can be completely disabled, or enabled.
  b, The parameters of this feature can be customized in everyone's own flawor. (I'd offer a variety of settings like in the emulator).

Here is an example without claiming completeness:
![kép](https://user-images.githubusercontent.com/84271678/120606478-82bfcb00-c44f-11eb-9d39-d8b769f79707.png)

These settings are only initial settings for new machines, won't change anything in existing ones.
The specific appearance of previously created VMs still can be changed from 86Box, and per-machine. 

Is such a solution is appropriate, what do you think?

**Comment by JustinJ553** [comment]
That solution is good. You could probably add "Use the settings from previous machine".

**Comment by laciba96** [comment]
I'll see what I can do about it. If there is progress I will indicate.
These new features are likely to be available in the next version.

**Comment by JustinJ553** [comment]
Don't forget the discord integration

**Comment by laciba96** [comment]
The new feature is implemented in v1.12, also with the ability to choose Discord integration.
